{
 "title": "Demo dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(process_automatically_risk_rating_bucket, decision_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Manually processed (last 5 min)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "increase(process_automatically_risk_rating_bucket{decision_namespace=\"$namespace\",le=\"0.0\"}[5m])"
    }
   ]
  },
  {
   "title": "Automatically processed (last 5 min)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "increase(process_automatically_risk_rating_bucket{decision_namespace=\"$namespace\",le=\"1.0\"}[5m])"
    }
   ]
  },
  {
   "title": "Automatic vs Manual (Total)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_automatically_risk_rating_bucket{decision_namespace=\"$namespace\", le=\"0.0\"}",
     "legendFormat": "Manual"
    },
    {
     "expr": "process_automatically_risk_rating_bucket{decision_namespace=\"$namespace\", le=\"1.0\"}",
     "legendFormat": "Automatic"
    }
   ]
  },
  {
   "title": "Cardholder Risk",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "increase(cardholder_risk_rating_bucket{decision_namespace=\"$namespace\"}[10s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Dispute Risk",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "increase(dispute_risk_rating_bucket{decision_namespace=\"$namespace\"}[10s])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}